DELETE FROM pres_races;
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (2016,"Hillary Clinton","Donald Trump","R");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (2012,"Barack Obama","Mitt Romney","D");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (2008,"Barack Obama","John McCain","D");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (2004,"John Kerry","George W. Bush","R");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (2000,"Al Gore","George W. Bush","R");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (1996,"Bill Clinton","Bob Dole","D");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (1992,"Bill Clinton","George H. W. Bush","D");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (1988,"Michael Dukakis","George H. W. Bush","R");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (1984,"Walter Mondale","Ronald Reagan","R");
INSERT INTO pres_races (race_year,dem_candidate,rep_candidate,winning_party) VALUES (1980,"Jimmy Carter","Ronald Reagan","R");
